<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
	</array>
	<key>injectionSelector</key>
	<string>L:text.html.rmarkdown</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inline</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#fenced_block_ruby</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced_block_javascript</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced_block_coffee</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced_block_elixir</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced_block_shell</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced_block_haml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced_block_html</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced_block_r</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced_block_c</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced_block_cpp</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced_block_yaml</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#fenced_block</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link-def</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#html</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#paragraph</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>fenced_block_c</key>
				<dict>
					<key>begin</key>
					<string>(^|\G)([`]{3})\{*[ ]*(?:c|C)\s*\}*$</string>
					<key>end</key>
					<string>(^|\G)([`]{3})($|\z)</string>
					<key>name</key>
					<string>meta.embedded.block.c</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.c</string>
						</dict>
					</array>
				</dict>
				<key>fenced_block_coffee</key>
				<dict>
					<key>begin</key>
					<string>(^|\G)([`]{3})[ ]*(?:coffee|coffeescript)$</string>
					<key>end</key>
					<string>(^|\G)([`]{3})($|\z)</string>
					<key>name</key>
					<string>meta.embedded.block.coffee</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.coffee</string>
						</dict>
					</array>
				</dict>
				<key>fenced_block_cpp</key>
				<dict>
					<key>begin</key>
					<string>(^|\G)([`]{3})\{*[ ]*(?:cpp|c\+\+|C\+\+).*\}*$</string>
					<key>end</key>
					<string>(^|\G)([`]{3})($|\z)</string>
					<key>name</key>
					<string>meta.embedded.block.cpp</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.cpp</string>
						</dict>
					</array>
				</dict>
				<key>fenced_block_elixir</key>
				<dict>
					<key>begin</key>
					<string>(^|\G)([`]{3})[ ]*(?:elixir)$</string>
					<key>end</key>
					<string>(^|\G)([`]{3})($|\z)</string>
					<key>name</key>
					<string>meta.embedded.block.elixer</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.elixir</string>
						</dict>
					</array>
				</dict>
				<key>fenced_block_haml</key>
				<dict>
					<key>begin</key>
					<string>(^|\G)([`]{3})[ ]*(?:haml)$</string>
					<key>end</key>
					<string>(^|\G)([`]{3})($|\z)</string>
					<key>name</key>
					<string>meta.embedded.block.haml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.haml</string>
						</dict>
					</array>
				</dict>
				<key>fenced_block_html</key>
				<dict>
					<key>begin</key>
					<string>(^|\G)([`]{3})[ ]*(?:html)$</string>
					<key>end</key>
					<string>(^|\G)([`]{3})($|\z)</string>
					<key>name</key>
					<string>meta.embedded.block.html</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>text.html.basic</string>
						</dict>
					</array>
				</dict>
				<key>fenced_block_javascript</key>
				<dict>
					<key>begin</key>
					<string>(^|\G)([`]{3})[ ]*(?:js|javascript)$</string>
					<key>end</key>
					<string>(^|\G)([`]{3})($|\z)</string>
					<key>name</key>
					<string>meta.embedded.block.js</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.js</string>
						</dict>
					</array>
				</dict>
				<key>fenced_block_r</key>
				<dict>
					<key>begin</key>
					<string>(^|\G)([`]{3})\{*[ ]*(?:r|R).*\}*$</string>
					<key>end</key>
					<string>(^|\G)([`]{3})($|\z)</string>
					<key>name</key>
					<string>meta.embedded.block.r</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.r</string>
						</dict>
					</array>
				</dict>
				<key>fenced_block_ruby</key>
				<dict>
					<key>begin</key>
					<string>(^|\G)([`]{3})[ ]*(?:rb|ruby)$</string>
					<key>end</key>
					<string>(^|\G)([`]{3})($|\z)</string>
					<key>name</key>
					<string>meta.embedded.block.ruby</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.ruby</string>
						</dict>
					</array>
				</dict>
				<key>fenced_block_shell</key>
				<dict>
					<key>begin</key>
					<string>(^|\G)([`]{3})[ ]*(?:bash|shell|sh)$</string>
					<key>end</key>
					<string>(^|\G)([`]{3})($|\z)</string>
					<key>name</key>
					<string>meta.embedded.block.shell</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.shell</string>
						</dict>
					</array>
				</dict>
				<key>fenced_block_yaml</key>
				<dict>
					<key>begin</key>
					<string>(^|\G)([`]{3})\{*[ ]*(?:yaml|YAML).*\}*$</string>
					<key>end</key>
					<string>(^|\G)([`]{3})($|\z)</string>
					<key>name</key>
					<string>meta.embedded.block.yaml</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.yaml</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
		<key>inline</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#code-inline-r</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>code-inline-r</key>
				<dict>
					<key>begin</key>
					<string>(`[r|R][ ]+)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.rmarkdown</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(`)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.raw.rmarkdown</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.embedded.block.r</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.r</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.html.markdown.redcarpet</string>
	<key>uuid</key>
	<string>BE79A69A-B9F5-4BCD-9068-893496E86663</string>
</dict>
</plist>
