<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
	</array>
	<key>injectionSelector</key>
	<string>L:source.cpp</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#block</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#rcpp</string>
				</dict>
			</array>
			<key>repository</key>
			<dict>
				<key>rcpp</key>
				<dict>
					<key>begin</key>
					<string>(^|\G)(/[\*]{3}\sR\s*)$</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.block.cpp</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(^|\G)(\*/\s*)($|\z)</string>
					<key>captures</key>
					<dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>comment.block.cpp</string>
						</dict>
					</dict>					<key>contentName</key>
					<string>meta.embedded.block.r</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.r</string>
						</dict>
					</array>
				</dict>
			</dict>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>comment.block.r</string>
</dict>
</plist>
