name: main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: r-lib/actions/setup-r@f9a764fea8d5c63df6ef9a5c7795bf7deb5d7e05 # v2
        with:
          use-public-rspm: true
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: 'npm'
      - run: npm install
      - name: Install remotes
        run: install.packages("remotes")
        shell: Rscript {0}
      - run: npm run build
      - name: Run sess tests
        run: tinytest::test_package("sess")
        shell: Rscript {0}
      - name: Run tests (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run -a npm run test
      - name: Run tests
        if: runner.os != 'Linux'
        run: npm run test
  build:
    runs-on: ubuntu-latest
    env:
      VSIX_FILE: vscode-R.vsix
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: 'npm'
      - run: npm install
      - name: Package extension
        run: npx @vscode/vsce package -o $VSIX_FILE
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ env.VSIX_FILE }}
          path: ${{ env.VSIX_FILE }}
  lint:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: r-lib/actions/setup-r@f9a764fea8d5c63df6ef9a5c7795bf7deb5d7e05 # v2
        with:
          use-public-rspm: true
      - name: Install lintr
        run: install.packages("lintr")
        shell: Rscript {0}

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: 'npm'

      - run: npm install
      - name: eslint
        run: npx eslint src --ext ts  

      - name: Lint R directory
        run: lintr::lint_dir("./R")
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true

      - name: Lint root directory
        run: lintr::lint_package("sess")
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
