name: pre-release

# creates/updates a pre-release with the .vsix 

on:
  push:
    branches: ["master"]

env:
  FILE_OUT: r-latest.vsix
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VSIX_FILE: vscode-R.vsix    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm install
      - name: Package extension
        run: npx @vscode/vsce package -o $VSIX_FILE
      - uses: actions/upload-artifact@v4
        with:
          name: "${{ env.VSIX_FILE }}"
          path: "${{ env.VSIX_FILE }}"

  pre-release:
    name: Pre-Release
    needs: build
    runs-on: ubuntu-latest
    env:
      VSIX_FILE: vscode-R.vsix    
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "${{ env.VSIX_FILE }}"
          path: "artifacts/"
      - name: Create or update pre-release
        run: |
          gh release delete latest --yes || true
          git tag -d latest || true
          git tag latest
          git push origin latest --force
          gh release create latest artifacts/${{ env.VSIX_FILE }}/${{ env.VSIX_FILE }} \
            --title "Development Build" \
            --notes "Contains the vsix-file from the latest push to master." \
            --prerelease
